services:
  - type: web
    name: URL-Shortener
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_folder.main:app --host 0.0.0.0 --port $PORT